# Generated by Django 3.1.6 on 2021-02-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0006_auto_20210219_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-01'),
            preserve_default=False,
        ),
    ]
