# Generated by Django 3.1.6 on 2021-02-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0007_auto_20210219_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date']},
        ),
    ]
