# Generated by Django 3.1.6 on 2021-02-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0009_team_teama_teamb_wager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wager',
            new_name='Bet',
        ),
    ]
