# Generated by Django 3.1.6 on 2021-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0010_auto_20210224_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='match_result',
            field=models.CharField(choices=[('TeamA Win', 'TeamA Win'), ('TeamB Win', 'TeamB Win'), ('TeamA Lose', 'TeamA Lose'), ('TeamB Lose', 'TeamB Lose'), ('Tie', 'Tie')], max_length=10),
        ),
    ]
