# Generated by Django 3.1.6 on 2021-02-24 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CyberUser', '0011_auto_20210224_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='teamA',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='teamB',
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='match_result',
            field=models.CharField(choices=[('TeamA Win', 'TeamA Win'), ('TeamB Win', 'TeamB Win'), ('Tie', 'Tie')], max_length=50),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.CharField(choices=[('Starting soon', 'Starting soon'), ('Live', 'Live'), ('Finished', 'Finished')], max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyberUser.teama')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyberUser.teamb')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CyberUser.match'),
            preserve_default=False,
        ),
    ]
