# Generated by Django 3.1.6 on 2021-02-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0014_match_match_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
