# Generated by Django 3.1.6 on 2021-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0016_auto_20210226_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='match_stat',
            field=models.CharField(choices=[('Starting soon', 'Starting soon'), ('Live', 'Live'), ('Finished', 'Finished')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
