# Generated by Django 3.1.6 on 2021-02-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0017_bet_match_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='match_stat',
            field=models.CharField(default='Finished', max_length=50),
        ),
    ]
