# Generated by Django 3.1.6 on 2021-02-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0018_auto_20210226_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='match_stat',
            field=models.CharField(choices=[('Starting soon', 'Starting soon'), ('Live', 'Live'), ('Finished', 'Finished')], max_length=50),
        ),
    ]
