# Generated by Django 3.1.6 on 2021-03-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0019_auto_20210226_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='match_stat',
        ),
    ]
