# Generated by Django 3.1.6 on 2021-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0020_remove_bet_match_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='rateA',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='rateB',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
