# Generated by Django 3.1.6 on 2021-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberUser', '0021_auto_20210303_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='rateA',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bet',
            name='rateB',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
